title: Georgia Christodoulou # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am pursing a MS degree in Business Analytics and an MBA at The University of Utah.
  <br><br>
  I am currently an Inventory Manager at Pattern with a focus on new brand assortment and initial orders.
  <br><br>
  <a href="https://www.linkedin.com/in/georgia-christodoulou-29a187120/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
